# Generated by Django 5.2.6 on 2025-09-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
